apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-deploy
  template:
    metadata:
      labels:
        app: gke-deploy
    spec:
      containers:
      - name: app
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-00-998e161ffd7e/demo-repo/demo
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gke-svc
spec:
  type: LoadBalancer
  selector:
    app: gke-deploy
  ports:
  - port: 80
    targetPort: 8000